apiVersion: v1
kind: Service
metadata:
  name: loki
  namespace: monitoring
  labels:
    app: loki
spec:
  type: NodePort
  ports:
    - name: loki
      port: 3100
      targetPort: 3100
      protocol: TCP
    - name: volume-exporter-loki-sidecar
      port: 9888
      targetPort: 9888
      protocol: TCP
  selector:
    app: loki